[package]
name = "twitch-cli"
version = "0.2.0"
authors = ["Consti <consti.loew@live.de>"]
edition = "2021"

[dependencies]
anyhow = "1.0.66"
reqwest = { version = "0.11.12", features = ["blocking"] }
serde_json = "1.0.87"
clap = "2.19.0"
